#ifndef GBX_ENUMS_MQH
#define GBX_ENUMS_MQH

enum ENUM_GBX_ACTION
  {
   GBX_ACTION_WAIT = 0,
   GBX_ACTION_BUY,
   GBX_ACTION_SELL,
   GBX_ACTION_NO_TRADE
  };

enum ENUM_GBX_DIRECTION
  {
   GBX_DIRECTION_NEUTRAL = 0,
   GBX_DIRECTION_BULLISH,
   GBX_DIRECTION_BEARISH
  };

enum ENUM_GBX_MARKET_REGIME
  {
   GBX_REGIME_UNKNOWN = 0,
   GBX_REGIME_BULLISH_TREND,
   GBX_REGIME_BEARISH_TREND,
   GBX_REGIME_FORMING_TREND,
   GBX_REGIME_EXHAUSTING_TREND,
   GBX_REGIME_CLEAN_RANGE,
   GBX_REGIME_NOISY_RANGE,
   GBX_REGIME_COMPRESSION,
   GBX_REGIME_POTENTIAL_BREAKOUT,
   GBX_REGIME_FALSE_BREAKOUT,
   GBX_REGIME_HIGH_VOLATILITY,
   GBX_REGIME_POST_NEWS,
   GBX_REGIME_UNTRADEABLE,
   GBX_REGIME_UNCERTAIN
  };

enum ENUM_GBX_MARKET_FAVORABILITY
  {
   GBX_FAVORABILITY_UNKNOWN = 0,
   GBX_FAVORABILITY_FAVORABLE,
   GBX_FAVORABILITY_NEUTRAL,
   GBX_FAVORABILITY_UNFAVORABLE,
   GBX_FAVORABILITY_BLOCKED
  };

enum ENUM_GBX_RISK_PROFILE
  {
   GBX_RISK_CONSERVATIVE = 0,
   GBX_RISK_BALANCED,
   GBX_RISK_AGGRESSIVE
  };

enum ENUM_GBX_SESSION
  {
   GBX_SESSION_NONE = 0,
   GBX_SESSION_ASIA,
   GBX_SESSION_LONDON,
   GBX_SESSION_NEW_YORK,
   GBX_SESSION_OVERLAP
  };

enum ENUM_GBX_LOG_LEVEL
  {
   GBX_LOG_DEBUG = 0,
   GBX_LOG_INFO,
   GBX_LOG_WARNING,
   GBX_LOG_ERROR
  };

enum ENUM_GBX_TRADE_STATE
  {
   GBX_TRADE_IDLE = 0,
   GBX_TRADE_PENDING,
   GBX_TRADE_OPEN,
   GBX_TRADE_PARTIAL,
   GBX_TRADE_CLOSING,
   GBX_TRADE_CLOSED
  };

#endif
